import json
from datetime import datetime, timedelta

import numpy as np
import pandas as pd

# Create comprehensive expense tracking system for Mother-in-Law House

# Project constants
TOTAL_BUDGET = 1_300_000  # KES
PROJECT_START = datetime(2025, 9, 15)


# M-Pesa fee structure (KES)
def calculate_mpesa_fee(amount):
    """Calculate M-Pesa transaction fee based on amount"""
    if amount <= 49:
        return 0
    elif amount <= 100:
        return 1
    elif amount <= 500:
        return 5
    elif amount <= 1000:
        return 10
    elif amount <= 1500:
        return 15
    elif amount <= 3000:
        return 25
    elif amount <= 5000:
        return 40
    elif amount <= 7500:
        return 75
    elif amount <= 10000:
        return 96
    elif amount <= 15000:
        return 156
    elif amount <= 20000:
        return 171.5
    elif amount <= 35000:
        return 355
    elif amount <= 50000:
        return 455
    else:
        return 455  # Max fee for amounts above 50K


# September 15, 2025 expenses
expenses_data = [
    # Transport & Logistics
    {
        "date": "15/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Worker Transport",
        "description": "Transport for the Workers",
        "amount": 2000,
        "vendor": "Local Transport",
    },
    {
        "date": "15/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Material Transport",
        "description": "Transport ballast",
        "amount": 2500,
        "vendor": "Transport Company",
    },
    {
        "date": "15/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Material Transport",
        "description": "Transport blocks",
        "amount": 2500,
        "vendor": "Transport Company",
    },
    # Workers Accommodation
    {
        "date": "15/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Accommodation",
        "description": "Accommodation for the workers",
        "amount": 2000,
        "vendor": "Local Lodge",
    },
    {
        "date": "15/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Housing",
        "description": "House rented for the workers (monthly)",
        "amount": 4000,
        "vendor": "Property Owner",
    },
    {
        "date": "15/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Bedding",
        "description": "3 mattresses @2500 each",
        "amount": 7500,
        "vendor": "Furniture Store",
    },
    # Building Materials
    {
        "date": "15/09/2025",
        "category": "Building Materials",
        "subcategory": "Sand",
        "description": "Sand - 14 tonnes",
        "amount": 9600,
        "vendor": "Sand Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Building Materials",
        "subcategory": "Ballast",
        "description": "Ballast 7 tonnes",
        "amount": 17150,
        "vendor": "Ballast Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Building Materials",
        "subcategory": "Blocks",
        "description": "Blocks 300@52",
        "amount": 15600,
        "vendor": "Block Manufacturer",
    },
    {
        "date": "15/09/2025",
        "category": "Building Materials",
        "subcategory": "Cement",
        "description": "Simba cement 710 @50 bags",
        "amount": 35500,
        "vendor": "Cement Dealer",
    },
    # Hardware Items
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Sealants",
        "description": "Calafiator 1 ltr @1800",
        "amount": 1800,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": "Metal spades 550 @ 2",
        "amount": 1100,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Protective",
        "description": "Polythene Papers rolls 2300 @ 2",
        "amount": 4600,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Reinforcement",
        "description": "Hoop Iron 200 #4kg",
        "amount": 800,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": 'Nails 4" 200 @ 5kg',
        "amount": 1000,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": 'Nails 3" 200 @ 3kg',
        "amount": 600,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": 'Nails 2.5" 200 @3kg',
        "amount": 600,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Roofing",
        "description": 'Roofing poles 3" 250 @ 8',
        "amount": 2000,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": "Roofing Nails 300 @ 3kg",
        "amount": 900,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Sealing",
        "description": "Rubber maroon 200 @ 3pckts",
        "amount": 600,
        "vendor": "Hardware Store",
    },
    {
        "date": "15/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "Horse Pipe clear 0.5 X60ft @ 1400",
        "amount": 1400,
        "vendor": "Hardware Store",
    },
    # Metal & Steel
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Welding",
        "description": "Welding rods 650 @ 2 packets",
        "amount": 1300,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "Squaretube 1.5 X 1.5 900 @ 23 pcs",
        "amount": 20700,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "Squaretubes 1.5 X 1 800@ 16 pcs",
        "amount": 12800,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "Squaretubes 0.75 X 0.75 500 @17pcs",
        "amount": 8500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "Zed 0.75 850 @10pcs",
        "amount": 8500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "Squaretubes 1 X 1 600@4pcs",
        "amount": 2400,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Sheets",
        "description": "Blacksheet (18g) 3pcs 2400@3pcs",
        "amount": 7200,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Bars",
        "description": "Flatbar 0.5 X 0.125 850 @ 1pc",
        "amount": 850,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Bars",
        "description": "Flatbar 0.75 X 0.125 450 @ 10pcs",
        "amount": 4500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Accessories",
        "description": "Chappy 250 @ 3pcs",
        "amount": 750,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Bars",
        "description": "Round 16 100 @ 5ft",
        "amount": 500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Bars",
        "description": 'Flat busy 0.75 " 120 @ 26 pcs',
        "amount": 3120,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "T-bar 0.75 850 @ 1pc",
        "amount": 850,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Accessories",
        "description": "Down stopper 120 @12pcs",
        "amount": 1440,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Finishing",
        "description": "Sand Paper p36 100 @3ms",
        "amount": 300,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Tools",
        "description": "Cutting disk 250 @5pcs",
        "amount": 1250,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Tools",
        "description": "Grinding disk 250 @ 2pcs",
        "amount": 500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Paint",
        "description": "Undercoat paint 5 ltrs 1050 @ 1pc",
        "amount": 1050,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Paint",
        "description": "Thinner 5ltrs 1450 @ 1pc",
        "amount": 1450,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Tools",
        "description": 'Brush 2" 150 @2pcs',
        "amount": 300,
        "vendor": "Metal Supplier",
    },
    {
        "date": "15/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Accessories",
        "description": "Chappy Normal (complete) 650 @ 1pc",
        "amount": 650,
        "vendor": "Metal Supplier",
    },
    # Labor
    {
        "date": "15/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 2000,
        "vendor": "Worker",
    },
    {
        "date": "15/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    # Miscellaneous
    {
        "date": "15/09/2025",
        "category": "Miscellaneous",
        "subcategory": "Lost Payment",
        "description": "Overpayment not refunded",
        "amount": 1000,
        "vendor": "Unknown",
    },
    # September 16, 2025 expenses
    {
        "date": "16/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Welder deposit",
        "amount": 12000,
        "vendor": "Welder",
    },
    {
        "date": "16/09/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": "Wheelbarrow",
        "amount": 4350,
        "vendor": "Hardware Store",
    },
    {
        "date": "16/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": 'Tap 1/2"',
        "amount": 550,
        "vendor": "Hardware Store",
    },
    {
        "date": "16/09/2025",
        "category": "Hardware Items",
        "subcategory": "Storage",
        "description": "Blue drum",
        "amount": 2600,
        "vendor": "Hardware Store",
    },
    {
        "date": "16/09/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": 'Hacksaw 14"',
        "amount": 280,
        "vendor": "Hardware Store",
    },
    {
        "date": "16/09/2025",
        "category": "Building Materials",
        "subcategory": "Doors & Windows",
        "description": "Door Frames 6 @ 1200",
        "amount": 7200,
        "vendor": "Carpenter",
    },
    {
        "date": "16/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Worker Transport",
        "description": "Transport for two electricians to voi",
        "amount": 2700,
        "vendor": "Transport Service",
    },
    # Paid labor for 16/09/2025
    {
        "date": "16/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack - Daily Labor",
        "amount": 2000,
        "vendor": "Worker",
    },
    {
        "date": "16/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1 - Daily Labor",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "16/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1 - Daily Labor",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "16/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2 - Daily Labor",
        "amount": 600,
        "vendor": "Worker",
    },
    # September 17, 2025 expenses
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Electrician Labor for fixing wiring pipes and boxes",
        "amount": 10000,
        "vendor": "Electrician",
    },
    {
        "date": "17/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Worker Transport",
        "description": "Transport back to Nairobi",
        "amount": 2200,
        "vendor": "Transport Service",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": '15"X15" meterbox 1pc',
        "amount": 2300,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "8-way ccu 1pc",
        "amount": 3500,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "16pcs twin boxes",
        "amount": 800,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "13pcs single boxes",
        "amount": 450,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "60pcs 20mm conduits",
        "amount": 5400,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "3pcs 25mm conduits",
        "amount": 600,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "2pcs 32mm conduits",
        "amount": 520,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "80pcs 20mm couplers",
        "amount": 400,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "10pcs 25mm couplers",
        "amount": 200,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "3pcs 32mm couplers",
        "amount": 105,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "3pcs 32mm bends",
        "amount": 150,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "1pc masking tape",
        "amount": 250,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 4",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "17/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Food",
        "description": "Food for the workers",
        "amount": 3260,
        "vendor": "Local Vendor",
    },
    # September 18, 2025 expenses
    {
        "date": "18/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Hardware",
        "description": "Window locks 15 @120",
        "amount": 1800,
        "vendor": "Metal Supplier",
    },
    {
        "date": "18/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Sheets",
        "description": "Perforated sheet",
        "amount": 4400,
        "vendor": "Metal Supplier",
    },
    {
        "date": "18/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Finishing",
        "description": "Body filler",
        "amount": 2200,
        "vendor": "Metal Supplier",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Dennis",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 4",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 5",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "18/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Digging the septic tank (paid 4000 of 16000)",
        "amount": 4000,
        "vendor": "Excavation Worker",
    },
    # September 19, 2025 expenses
    {
        "date": "19/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "19/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "19/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "19/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "19/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "5pcs squaretube 3x3x3mm @ 6000",
        "amount": 30000,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "5pcs squaretube 3x2x2mm @ 3500",
        "amount": 17500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "4pcs 1.5x1.5x1.5mm @ 1650",
        "amount": 6600,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "5pcs 1x1x1.5mm @ 950",
        "amount": 4750,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Welding",
        "description": "2 packets welding rods @ 650",
        "amount": 1300,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Tools",
        "description": '2pcs grinding disk 7" @ 250',
        "amount": 500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Paint",
        "description": "4ltrs undercoat @ 1050",
        "amount": 4200,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Paint",
        "description": "5ltrs thinner @ 1450",
        "amount": 7250,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Sheets",
        "description": "2pcs plate 6x6 @ 6000",
        "amount": 12000,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "5pcs 0.75x0.75x18gm @ 500",
        "amount": 2500,
        "vendor": "Metal Supplier",
    },
    {
        "date": "19/09/2025",
        "category": "Hardware Items",
        "subcategory": "Water Storage",
        "description": "3,000 ltrs tank",
        "amount": 20000,
        "vendor": "Tank Supplier",
    },
    # September 20, 2025 expenses
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Excavation work payment",
        "amount": 5600,
        "vendor": "Excavation Worker",
    },
    {
        "date": "20/09/2025",
        "category": "Utilities",
        "subcategory": "Water",
        "description": "Water payment",
        "amount": 4400,
        "vendor": "Water Utility",
    },
    {
        "date": "20/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Plumber payment",
        "amount": 5000,
        "vendor": "Plumber",
    },
    # Additional September 20, 2025 plumbing and building materials
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "10pcs PPR Pipes 3/4 @ 350",
        "amount": 3500,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "20pcs PPR elbows 3/4 @ 40",
        "amount": 800,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '5pcs PPR female elbow 3/4 X 1/2" @ 90',
        "amount": 450,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "10pcs PPR Tee 25mm @ 40",
        "amount": 400,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '3pcs PPR female Tee 25mm x 1/2" @ 90',
        "amount": 270,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "2pcs connected stop cork @ 1200",
        "amount": 2400,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '5pcs Male adapters 25mm x 1/2" @ 90',
        "amount": 450,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "10pcs thread tape large @ 100",
        "amount": 1000,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Kitchen",
        "description": "1pc Kitchen sink",
        "amount": 1850,
        "vendor": "Hardware Store",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs waste pipe 1 1/2" @ 500',
        "amount": 1000,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs inspection tee 1 1/2" @ 160',
        "amount": 320,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "250ml tangit glue",
        "amount": 550,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "2pcs floor trap 4 way @ 550",
        "amount": 1100,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "1pc floor trap 1 way",
        "amount": 450,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs inspection bend 4" @ 380',
        "amount": 760,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '3pcs waste bend 4" @ 250',
        "amount": 750,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc vent cup 4"',
        "amount": 100,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "6pcs manhole cover 450x450mm @ 1200",
        "amount": 7200,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "2pcs bib tap @ 1200",
        "amount": 2400,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "3pcs Gate valve 3/4 @ 850",
        "amount": 2550,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "7pcs male adapters 25mm @ 100",
        "amount": 700,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc gulley trap 4"',
        "amount": 250,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '4pcs waste pipe 4" @ 450',
        "amount": 1800,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '3pcs PPR pipe 1" @ 450',
        "amount": 1350,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '5pcs PPR elbow 1" @ 80',
        "amount": 400,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '5pcs PPR Tee 1" @ 80',
        "amount": 400,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "40ft 4x2 cypress @ 58",
        "amount": 2320,
        "vendor": "Timber Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "180ft 3x2 cypress @ 47",
        "amount": 8460,
        "vendor": "Timber Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": '4kg nails 5" @ 200',
        "amount": 800,
        "vendor": "Hardware Store",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": "5kg binding @ 200",
        "amount": 1000,
        "vendor": "Hardware Store",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": "1pc mabati scissors",
        "amount": 1500,
        "vendor": "Hardware Store",
    },
    {
        "date": "20/09/2025",
        "category": "Building Materials",
        "subcategory": "Cement",
        "description": "40 bags simba cement @ 720",
        "amount": 28800,
        "vendor": "Cement Dealer",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '8pcs GT nipple 1/2" @ 30',
        "amount": 240,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '7pcs GT socket 1/2" @ 30',
        "amount": 210,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "20/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '8pcs GT plug 1/2" @ 50',
        "amount": 400,
        "vendor": "Plumbing Supplier",
    },
    # September 21, 2025 expenses
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "21/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Plumber payment",
        "amount": 10000,
        "vendor": "Plumber",
    },
    {
        "date": "21/09/2025",
        "category": "Utilities",
        "subcategory": "Water",
        "description": "Water payment",
        "amount": 180,
        "vendor": "Water Utility",
    },
    {
        "date": "21/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Logistics",
        "description": "Deo logistics",
        "amount": 550,
        "vendor": "Logistics Provider",
    },
    # Additional September 21, 2025 plumbing materials
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '4pcs waste pipe 4" @ 450',
        "amount": 1800,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '4pcs inspection tee 4" @ 250',
        "amount": 1000,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs inspection bend 4" @ 380',
        "amount": 760,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs waste bend 4" @ 250',
        "amount": 500,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc waste rest bend 4" x 2"',
        "amount": 220,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc waste coupling 4"',
        "amount": 150,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc Y junctions 4"',
        "amount": 150,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "2pcs PPR cap 25mm @ 40",
        "amount": 80,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '2pcs PPR caps 1" @ 80',
        "amount": 160,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "3pcs sink trap @ 100",
        "amount": 300,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '6pcs male adapters 1" @ 100',
        "amount": 600,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '6pcs female adapters 1" @ 100',
        "amount": 600,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "250ml tangit glue",
        "amount": 550,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc valve 3/4" brass',
        "amount": 1000,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "21/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '5m lay flat 1/2" @ 80',
        "amount": 400,
        "vendor": "Plumbing Supplier",
    },
    # September 22, 2025 expenses
    {
        "date": "22/09/2025",
        "category": "Utilities",
        "subcategory": "Water",
        "description": "Water 3000 ltrs @ 1250",
        "amount": 3750,
        "vendor": "Water Utility",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "220ft Faceboard 8X1 cypress @ 95",
        "amount": 20900,
        "vendor": "Timber Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": "3kg Roof Nails @ 300",
        "amount": 900,
        "vendor": "Hardware Store",
    },
    {
        "date": "22/09/2025",
        "category": "Hardware Items",
        "subcategory": "Roofing",
        "description": "2pkts rubbers cups @ 100",
        "amount": 200,
        "vendor": "Hardware Store",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "30ft 3X2 bluegum @ 35",
        "amount": 1050,
        "vendor": "Timber Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "50ft 6X1 bluegum @ 40",
        "amount": 2000,
        "vendor": "Timber Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Roofing",
        "description": "15pcs 3mtr Iron sheets @ 1650",
        "amount": 24750,
        "vendor": "Roofing Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Roofing",
        "description": "6pcs ridges maasai red @ 650",
        "amount": 3900,
        "vendor": "Roofing Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": '1pc PVC pipe 4" @ 1500',
        "amount": 1500,
        "vendor": "Plumbing Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Hardware Items",
        "subcategory": "Electrical",
        "description": "5pcs Dio @ 950",
        "amount": 4750,
        "vendor": "Electrical Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "40ft 6x9 @ 45",
        "amount": 1800,
        "vendor": "Timber Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Metal & Steel",
        "subcategory": "Structure",
        "description": "3pcs squaretube 1 1/2x1 @ 800",
        "amount": 2400,
        "vendor": "Metal Supplier",
    },
    {
        "date": "22/09/2025",
        "category": "Hardware Items",
        "subcategory": "Hardware",
        "description": "2 pairs flap hinges @ 150",
        "amount": 300,
        "vendor": "Hardware Store",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Welder payment",
        "amount": 10000,
        "vendor": "Welder",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "22/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    # September 23, 2025 expenses
    {
        "date": "23/09/2025",
        "category": "Building Materials",
        "subcategory": "Sand",
        "description": "Sand",
        "amount": 4550,
        "vendor": "Sand Supplier",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "23/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    # September 24, 2025 expenses
    {
        "date": "24/09/2025",
        "category": "Utilities & Services",
        "subcategory": "Water Connection",
        "description": "Water connection",
        "amount": 5100,
        "vendor": "Water Company",
    },
    {
        "date": "24/09/2025",
        "category": "Hardware Items",
        "subcategory": "Tools & Supplies",
        "description": "Rope",
        "amount": 750,
        "vendor": "Hardware Store",
    },
    {
        "date": "24/09/2025",
        "category": "Hardware Items",
        "subcategory": "Roofing Materials",
        "description": "2kg roofing nails @ 300 each",
        "amount": 600,
        "vendor": "Hardware Store",
    },
    {
        "date": "24/09/2025",
        "category": "Hardware Items",
        "subcategory": "Roofing Materials",
        "description": "2 packets roofing rubbers @ 100 each",
        "amount": 200,
        "vendor": "Hardware Store",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 1",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 2",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 3",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 4",
        "amount": 600,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 4",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Helper 5",
        "amount": 600,
        "vendor": "Worker",
    },
    # September 25, 2025 expenses
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialist Labor",
        "description": "Water connection labor",
        "amount": 8000,
        "vendor": "Labor Contractor",
    },
    {
        "date": "25/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Worker Transport",
        "description": "Transport",
        "amount": 600,
        "vendor": "Transport Service",
    },
    {
        "date": "25/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Worker Transport",
        "description": "Fundi transport",
        "amount": 3500,
        "vendor": "Transport Service",
    },
    {
        "date": "25/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Meals",
        "description": "Fundi extra meal",
        "amount": 1000,
        "vendor": "Food Vendor",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 rolls PPR pipe 3/4 @ 5500 each",
        "amount": 11000,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "1 pc tap @ 600",
        "amount": 600,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs G.I Tee 1/2 @ 50 each",
        "amount": 100,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs G.I socket 1/2 @ 30 each",
        "amount": 60,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs G.I bend 1/2 @ 100 each",
        "amount": 200,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "4 pcs G.I elbow @ 30 each",
        "amount": 120,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "4 pcs G.I nipple 1/2 @ 30 each",
        "amount": 120,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs threadtape large @ 100 each",
        "amount": 200,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "3 pcs G.I union 1/2 @ 100 each",
        "amount": 300,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "20 mtrs PPR pipe 1/2 @ 50 per meter",
        "amount": 1000,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs reducer 3/4 x 1/2 @ 80 each",
        "amount": 160,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "1 pc gate valve 3/4 @ 850",
        "amount": 850,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "1 pc G.I tee 3/4 @ 40",
        "amount": 40,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs union 3/4 @ 130 each",
        "amount": 260,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "1 pc socket 1/2 @ 30",
        "amount": 30,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "1 pc stop cock @ 1200",
        "amount": 1200,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing Supplies",
        "description": "2 pcs gate valve 1/2 @ 650 each",
        "amount": 1300,
        "vendor": "Hardware Store",
    },
    {
        "date": "25/09/2025",
        "category": "Miscellaneous",
        "subcategory": "Tips",
        "description": "Tip",
        "amount": 500,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "8 fundis @ 1200 each",
        "amount": 9600,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "11 helpers @ 600 each",
        "amount": 6600,
        "vendor": "Worker",
    },
    {
        "date": "25/09/2025",
        "category": "Miscellaneous",
        "subcategory": "Not used for the project",
        "description": "Money taken for personal use and potential overcharges or unaccounted expenses.",
        "amount": 79401.50,
        "vendor": "Self",
    },
    {
        "date": "24/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialized Labor",
        "description": "Welder - final balance payment (18000 of 40000 total)",
        "amount": 18000,
        "vendor": "Welder",
    },
    {
        "date": "25/09/2025",
        "category": "Labor Costs",
        "subcategory": "Specialized Labor",
        "description": "Excavation Worker - final balance payment (6400 of 16000 total)",
        "amount": 6400,
        "vendor": "Excavation Worker",
    },
    # Friday 26/09/2025 expenses
    {
        "date": "26/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 Fundi @ 1300 each",
        "amount": 3900,
        "vendor": "Worker",
    },
    {
        "date": "26/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "2 Fundi @ 1200 each",
        "amount": 2400,
        "vendor": "Worker",
    },
    {
        "date": "26/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "5 helpers @ 600 each",
        "amount": 3000,
        "vendor": "Worker",
    },
    {
        "date": "26/09/2025",
        "category": "Transport & Logistics",
        "subcategory": "Transport",
        "description": "Transport on boda",
        "amount": 300,
        "vendor": "Transport",
    },
    {
        "date": "26/09/2025",
        "category": "Building Materials",
        "subcategory": "Sand",
        "description": "Sand 14 tonnes",
        "amount": 9000,
        "vendor": "Supplier",
    },
    {
        "date": "26/09/2025",
        "category": "Utilities",
        "subcategory": "Water",
        "description": "Water",
        "amount": 1200,
        "vendor": "Supplier",
    },
    {
        "date": "26/09/2025",
        "category": "Building Materials",
        "subcategory": "Cement",
        "description": "20 bags cement @ 720 each",
        "amount": 14400,
        "vendor": "Supplier",
    },
    {
        "date": "26/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "1 pc G.I union 3/4 @ 130",
        "amount": 130,
        "vendor": "Hardware Store",
    },
    {
        "date": "26/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "1 pc G.I R/Socket 3/4 x 1/2 @ 80",
        "amount": 80,
        "vendor": "Hardware Store",
    },
    {
        "date": "26/09/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "1 pc G.I play 1/2 @ 40",
        "amount": 40,
        "vendor": "Hardware Store",
    },
    # Saturday wages 27/09/2025
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 4",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 5",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "5 helpers @ 600 each",
        "amount": 3000,
        "vendor": "Worker",
    },
    {
        "date": "27/09/2025",
        "category": "Workers Accommodation",
        "subcategory": "Food",
        "description": "Meat for workers",
        "amount": 1000,
        "vendor": "Supplier",
    },
    # Sunday 28/09/2025 labor
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 4",
        "amount": 1200,
        "vendor": "Worker",
    },
    {
        "date": "28/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "4 helpers @ 600 each",
        "amount": 2400,
        "vendor": "Worker",
    },
    # Monday 29/09/2025 labor
    {
        "date": "29/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "29/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "29/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "29/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "29/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Monday 29/09/2025 materials
    {
        "date": "29/09/2025",
        "category": "Building Materials",
        "subcategory": "Cement",
        "description": "30 bags cement @ 720 each",
        "amount": 21600,
        "vendor": "Supplier",
    },
    {
        "date": "29/09/2025",
        "category": "Building Materials",
        "subcategory": "Stones",
        "description": "262ft 6X9 stones @ 42 sh per ft",
        "amount": 11790,
        "vendor": "Supplier",
    },
    # Tuesday 30/09/2025 labor
    {
        "date": "30/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "30/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "30/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "30/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "30/09/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Tuesday 30/09/2025 utilities
    {
        "date": "30/09/2025",
        "category": "Utilities",
        "subcategory": "Water",
        "description": "Water",
        "amount": 1200,
        "vendor": "Supplier",
    },
    # Wednesday 01/10/2025 labor
    {
        "date": "01/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "01/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "01/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "01/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "01/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Thursday 02/10/2025 labor
    {
        "date": "02/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "02/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "02/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "02/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "02/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Thursday 02/10/2025 supplies
    {
        "date": "02/10/2025",
        "category": "Workers Accommodation",
        "subcategory": "Food Supplies",
        "description": "Unga and cooking oil for workers",
        "amount": 2700,
        "vendor": "Supplier",
    },
    # Thursday 02/10/2025 provisions
    {
        "date": "02/10/2025",
        "category": "Workers Accommodation",
        "subcategory": "Food",
        "description": "Unga and cooking oil for workers",
        "amount": 2700,
        "vendor": "Supplier",
    },
    # Friday 03/10/2025 labor
    {
        "date": "03/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "03/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "03/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "03/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "03/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Friday 04/10/2025 labor
    {
        "date": "04/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "04/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "04/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "04/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "04/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Friday 04/10/2025 materials and transport
    {
        "date": "04/10/2025",
        "category": "Transport & Logistics",
        "subcategory": "Transport",
        "description": "Transport",
        "amount": 1000,
        "vendor": "Transport Service",
    },
    {
        "date": "04/10/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "Timber 6X1 80ft @ 40",
        "amount": 3200,
        "vendor": "Timber Supplier",
    },
    {
        "date": "04/10/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "Timber 3X2 20ft @ 35",
        "amount": 700,
        "vendor": "Timber Supplier",
    },
    {
        "date": "04/10/2025",
        "category": "Building Materials",
        "subcategory": "Cement",
        "description": "50 bags cement @ 710 each",
        "amount": 35500,
        "vendor": "Cement Dealer",
    },
    {
        "date": "04/10/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": "1 pc D10 @ 950",
        "amount": 950,
        "vendor": "Hardware Store",
    },
    {
        "date": "04/10/2025",
        "category": "Hardware Items",
        "subcategory": "Tools",
        "description": "1 pc D8 @ 650",
        "amount": 650,
        "vendor": "Hardware Store",
    },
    # Sunday 06/10/2025 labor - UNPAID
    {
        "date": "06/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack - UNPAID",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "06/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "06/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "06/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "06/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each - UNPAID",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Monday 07/10/2025 labor - UNPAID
    {
        "date": "07/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack - UNPAID",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "07/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "07/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "07/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "07/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each - UNPAID",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Tuesday 08/10/2025 labor - UNPAID
    {
        "date": "08/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Jack - UNPAID",
        "amount": 1500,
        "vendor": "Worker",
    },
    {
        "date": "08/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 1 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "08/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 2 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "08/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "Fundi 3 - UNPAID",
        "amount": 1300,
        "vendor": "Worker",
    },
    {
        "date": "08/10/2025",
        "category": "Labor Costs",
        "subcategory": "Daily Labor",
        "description": "3 helpers @ 600 each - UNPAID",
        "amount": 1800,
        "vendor": "Worker",
    },
    # Wednesday 08/10/2025 materials and supplies
    {
        "date": "08/10/2025",
        "category": "Building Materials",
        "subcategory": "Wood",
        "description": "2x2 timber 800ft @ 22",
        "amount": 17600,
        "vendor": "Timber Supplier",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Ventilation",
        "description": "2 window vents @ 100 each",
        "amount": 200,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Transport & Logistics",
        "subcategory": "Transport",
        "description": "Transport",
        "amount": 200,
        "vendor": "Transport Service",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": '8kg nails 4" @ 200',
        "amount": 1600,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": '10kg nails 3" @ 200',
        "amount": 2000,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": '2 packets steel nail 3" @ 350',
        "amount": 700,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Plumbing",
        "description": "1 pc manhole cover 18x18 @ 1200",
        "amount": 1200,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Sealants",
        "description": "2 pcs silicon clear @ 350",
        "amount": 700,
        "vendor": "Hardware Store",
    },
    {
        "date": "08/10/2025",
        "category": "Hardware Items",
        "subcategory": "Fasteners",
        "description": '2kg nails 2.5" @ 200',
        "amount": 400,
        "vendor": "Hardware Store",
    },
]

# Calculate M-Pesa fees for each expense
for expense in expenses_data:
    # For unpaid expenses, set M-Pesa fee to 0 and mark as unpaid
    if "UNPAID" in expense["description"]:
        expense["mpesa_fee"] = 0.0
        expense["total_cost"] = 0.0  # Don't count in spending until paid
        expense["status"] = "unpaid"
    else:
        expense["mpesa_fee"] = calculate_mpesa_fee(expense["amount"])
        expense["total_cost"] = expense["amount"] + expense["mpesa_fee"]
        expense["status"] = "paid"

# Create DataFrame
df = pd.DataFrame(expenses_data)

# Calculate summary statistics (only paid expenses)
paid_df = df[df["status"] == "paid"]
total_spent = paid_df["amount"].sum()
total_mpesa_fees = paid_df["mpesa_fee"].sum()
total_cost = paid_df["total_cost"].sum()
balance_remaining = TOTAL_BUDGET - total_cost
percentage_used = (total_cost / TOTAL_BUDGET) * 100

# Calculate total outstanding amounts (moved earlier for calculations)
outstanding_balances = [
    {
        "vendor": "Electrician",
        "description": "Remaining balance for electrical work (18000 of 28000)",
        "amount": 18000,
        "due_date": "To be scheduled",
    },
    {
        "vendor": "Plumber",
        "description": "Remaining balance for plumbing work (12000 of 27000)",
        "amount": 12000,
        "due_date": "To be scheduled",
    },
]

# Unpaid labor expenses - extract from DataFrame
unpaid_df = df[df["status"] == "unpaid"]
unpaid_expenses = unpaid_df.to_dict("records")

total_outstanding = sum(balance["amount"] for balance in outstanding_balances)
total_unpaid_labor = sum(expense["amount"] for expense in unpaid_expenses)
total_pending = total_outstanding + total_unpaid_labor

# Calculate inclusive budget percentages
total_committed = total_cost + total_pending  # All spent + all outstanding/unpaid
percentage_used_inclusive = (total_committed / TOTAL_BUDGET) * 100
effective_balance = TOTAL_BUDGET - total_committed

# Category summary (only paid expenses)
category_summary = (
    paid_df.groupby("category")
    .agg({"amount": "sum", "mpesa_fee": "sum", "total_cost": "sum"})
    .reset_index()
)

# Calculate budget percentage and sort by it (descending)
category_summary["budget_percentage"] = (
    category_summary["total_cost"] / TOTAL_BUDGET
) * 100
category_summary = category_summary.sort_values(
    "budget_percentage", ascending=False
).reset_index(drop=True)

# Calculate budget percentage and sort by it (descending)
category_summary["budget_percentage"] = (
    category_summary["total_cost"] / TOTAL_BUDGET
) * 100
category_summary = category_summary.sort_values(
    "budget_percentage", ascending=False
).reset_index(drop=True)

# Print summary for verification
print("=== MOTHER-IN-LAW HOUSE EXPENSE SUMMARY ===")
print(f"Date: {PROJECT_START.strftime('%d/%m/%Y')}")
print(f"Total Budget: KES {TOTAL_BUDGET:,}")
print(f"Total Spent (Paid): KES {total_spent:,}")
print(f"M-Pesa Fees: KES {total_mpesa_fees:,}")
print(f"Total Cost (inc. fees): KES {total_cost:,}")
print(f"Balance Remaining: KES {balance_remaining:,}")
print(f"Budget Used (Paid Only): {percentage_used:.2f}%")
print()
print("=== OUTSTANDING AMOUNTS ===")
print(f"Outstanding Balances: KES {total_outstanding:,}")
print(f"Unpaid Labor: KES {total_unpaid_labor:,}")
print(f"Total Pending: KES {total_pending:,}")
print(f"Total Committed (Paid + Pending): KES {total_committed:,}")
print(f"Budget Used (Inclusive): {percentage_used_inclusive:.2f}%")
print(f"Effective Balance: KES {effective_balance:,}")
print()

print("=== CATEGORY BREAKDOWN ===")
for _, row in category_summary.iterrows():
    print(
        f"{row['category']}: KES {row['total_cost']:,} (Amount: {row['amount']:,} + Fees: {row['mpesa_fee']:,})"
    )

# Export data for HTML dashboard
dashboard_data = {
    "project_info": {
        "name": "Mother-in-Law House Completion",
        "start_date": "15/09/2025",
        "total_budget": TOTAL_BUDGET,
        "total_spent": int(total_spent),
        "total_mpesa_fees": int(total_mpesa_fees),
        "total_cost": int(total_cost),
        "balance_remaining": int(balance_remaining),
        "percentage_used": round(percentage_used, 2),
        "percentage_used_inclusive": round(percentage_used_inclusive, 2),
        "total_outstanding": int(total_outstanding),
        "total_unpaid_labor": int(total_unpaid_labor),
        "total_pending": int(total_pending),
        "total_committed": int(total_committed),
        "effective_balance": int(effective_balance),
    },
    "category_summary": category_summary.to_dict("records"),
    "daily_expenses": df.to_dict("records"),
    "outstanding_balances": outstanding_balances,
    "unpaid_expenses": unpaid_expenses,
    "last_updated": "24/09/2025 12:00:00",
}

# Save data for HTML dashboard
with open(
    "/Users/lemaiyan/dev/all/personal/mum-in-law-house/expense_data.json", "w"
) as f:
    json.dump(dashboard_data, f, indent=2)

print(f"\nData exported for HTML dashboard: {len(df)} transactions processed")
print(f"JSON file created: expense_data.json")
